#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <esp_codec_dev_types.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#define AUDIO_INPUT_MIC_GAIN_DB  30.0f

// Korvo-2 capture path matching Espressif ADF:
// ES7210 selects MIC1/MIC2/MIC3, I2S RX reads two 32-bit STD slots, and the
// four 16-bit lanes are fed to AFE as [ref, mic, unused, mic].
#define AUDIO_INPUT_REFERENCE true
#define AUDIO_KORVO2_AFE_INPUT_FORMAT "RMNM"
#define AUDIO_KORVO2_AFE_TOTAL_CH_NUM 4
#define AUDIO_KORVO2_AFE_MIC_NUM 2
#define AUDIO_KORVO2_AFE_REF_NUM 1
#define AUDIO_KORVO2_RX_STD_32BIT_MONO 0
#define AUDIO_KORVO2_RX_STD_32BIT_STEREO 1
#define AUDIO_KORVO2_CAPTURE_SLOT_COUNT 4
#define AUDIO_KORVO2_MIC_SLOT 1
#define AUDIO_KORVO2_MIC1_SLOT 3
#define AUDIO_KORVO2_REFERENCE_SLOT 0
#define AUDIO_KORVO2_ES7210_MIC_SELECTED 0x07
#define AUDIO_KORVO2_REF_PROBE 0
#define AUDIO_KORVO2_SLOT_MONITOR 0
#define AUDIO_KORVO2_SLOT_MONITOR_INTERVAL_MS 200
#define AUDIO_KORVO2_REF_PROBE_WINDOW_MS 200
#define AUDIO_KORVO2_REF_PROBE_MAX_DELAY_MS 400
#define AUDIO_KORVO2_REF_PROBE_STEP_MS 10
#define AUDIO_AFE_USE_SR_LOW_COST true
#define AUDIO_AFE_USE_VC_LOW_COST false
#define AUDIO_KORVO2_SOFTWARE_REF_DELAY_MS 0
#define AUDIO_KORVO2_ES8311_GPIO44 0x50

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_16
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_9
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_10
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_48
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_17
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_18
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#define AUDIO_INPUT_MIC_CHANNEL_MASK       (ESP_CODEC_DEV_MAKE_CHANNEL_MASK(0) | ESP_CODEC_DEV_MAKE_CHANNEL_MASK(1))
#define AUDIO_INPUT_REFERENCE_CHANNEL_MASK ESP_CODEC_DEV_MAKE_CHANNEL_MASK(2)

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define BUTTON_ADC_CHANNEL      ADC_CHANNEL_4
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
